site_name: The Nest
site_description: The Nest — Pigeon's safe space! Make yourself at home, it's alright. 🧡
site_author: Max Kerr (@thatgaypigeon)
copyright: 2023 © Max Kerr (@thatgaypigeon)

repo_url: https://github.com/thatgaypigeon/thatgaypigeon.github.io

docs_dir: src
site_dir: build

watch:
  - _components

theme:
  name: null
  locale: en
  custom_dir: _components
  include_sidebar: false

plugins:
  - redirects:
      redirect_maps:
        "discord.md": "https://discord.gg/aB4Bw5pyTS"
        "github.md": "https://github.com/thatgaypigeon"
        "source.md": "https://github.com/thatgaypigeon/thatgaypigeon.github.io"
        "wiki.md": "https://pigeon.miraheze.org/wiki/"
        "youtube.md": "https://youtube.com/@thatgaypigeon"

extra:
  version: 1.0
