family = "The Nest - Icon Font"
output_file = "build/TheNestIcons.ttf"
version_major = 1
version_minor = 0

upem = 1024
width = 1271
ascender = 800
descender = -64
linegap = 0

transform = "translate(0, 0)"
color_format = "glyf_colr_1"
reuse_tolerance = 0.1
ignore_reuse_error = true
keep_glyph_names = false
clip_to_viewbox = true
pretty_print = false

fea_file = "features.fea"
glyphmap_generator = "nanoemoji.write_glyphmap"
bitmap_resolution = 128
use_zopflipng = true
use_pngquant = true
pngquant_flags = "--speed 1 --skip-if-larger --quality 85-95"


[axis.wght]
name = "Weight"
default = 400

[master.regular]
style_name = "Regular"

[master.regular.position]
wght = 400
