return {
	["CHVRCHES"] = {
		albums = {
			["EP"] = "EP (CHVRCHES album)",
			["Recover EP"] = true, ["Recover"] = "Recover EP",
			["Gun EP"] = true, ["Gun"] = "Gun EP",
			["Lies EP"] = true, ["Lies"] = "Lies EP",
			["The Mother We Share EP"] = true, ["The Mother We Share"] = "The Mother We Share",
			["Under The Tide EP"] = true, ["Under The Tide"] = "Under The Tide EP",
			["The Bones of What You Believe"] = true,
			["Every Open Eye"] = true,
			["Love Is Dead"] = true,
			["Hansa Session"] = true,
			["In Search of Darkness"] = true,
			["Screen Violence"] = true,
		},
		songs = {
			["ZVVVL"] = true,
			["Now Is Not The Time"] = true,
			
			["The Mother We Share"] = true,
			["We Sink"] = true,
			["Gun"] = "Gun (CHVRCHES song)",
			["Tether"] = true,
			["Lies"] = "Lies (CHVRCHES song)",
			["Under The Tide"] = true,
			["Recover"] = true,
			["Night Sky"] = true,
			["Sciece/Visions"] = true,
			["Lungs"] = "Lungs (CHVRCHES song)",
			["By The Throat"] = true,
			["You Caught The Light"] = true,
			
			["Dead Air"] = true,
			
			["Never Ending Circles"] = true,
			["Leave A Trace"] = true,
			["Keep You On My Side"] = true,
			["Make Them Gold"] = true,
			["Clearest Blue"] = true,
			["High Enough To Carry You Over"] = true,
			["Empty Threat"] = true,
			["Down Side Of Me"] = true,
			["Playing Dead"] = true,
			["Bury It"] = true,
			["Afterglow"] = true,
			["Get Away"] = true,
			["Follow You"] = true,
			["Bow Down"] = true,
			["Warning Call"] = true,
			
			["Graffiti"] = "Graffiti (CHVRCHES song)",
			["Get Out"] = true,
			["Deliverance"] = true,
			["My Enemy"] = true,
			["Forever"] = "Forever (CHVRCHES song)",
			["Never Say Die"] = true,
			["Miracle"] = "Miracle (CHVRCHES song)",
			["Graves"] = "Graves (CHVRCHES song)",
			["Heaven/Hell"] = true,
			["God's Plan"] = true,
			["Really Gone"] = true,
			["ii"] = true,
			["Wonderland"] = "Wonderland (CHVRCHES song)",
			
			["Out of My Head"] = true,
			
			["Death Stranding"] = "Death Stranding (CHVRCHES song)",
			
			["Asking For A Friend"] = true,
			["he Said She Said"] = true,
			["California"] = "California (CHVRCHES song)",
			["Violent Delights"] = true,
			["How Not To Drown"] = true,
			["Final Girl"] = true,
			["Good Girls"] = true,
			["Lullabies"] = true,
			["Nightmares"] = true,
			["Better If You Don't"] = true,
			["Killer"] = "Killer (CHVRCHES song)",
			["Screaming"] = "Screaming (CHVRCHES song)",
			["Bitter End"] = true,
			
			["Over"] = "Over (CHVRCHES song)",
			
			["Manhattan"] = "Manhattan (CHVRCHES song)",
			["White Summer"] = true,
			["Talking In My Sleep"] = true,
			["City On Fire"] = true,
		}
	}
}