#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Build
if git diff --quiet HEAD -- ./src; then
    mkdocs gh-deploy --config-file ./mkdocs.yml --message "🛠️ Build [auto]"
fi

# Stash uncommitted changes
git stash save --keep-index

# Switch to gh-pages branch
git checkout gh-pages

# Add and commit changes in _static directory
git add "_static/*"
git commit -m "Update static files"

# Push changes to remote gh-pages branch
git push origin gh-pages

# Switch back to main branch
git checkout main

# Apply stashed changes
git stash pop
