#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

CLR='\033[38;2;255;150;0m'
BLD="\033[1m"
ITL="\033[3m"
UDL="\033[4m"

ERR="${R}${BLD}✗${RST}"
SUC="${G}${BLD}✓${RST}"

RST="\033[0m" # Reset

IND="→"

HD1="\n${CLR}${BLD}${IND}"
HD2="\n ${CLR}${IND}"

DONE="\nAll done! ✨ 🍰 ✨"

# Get the list of modified, added, or deleted files
files=$(git diff --staged --name-only --diff-filter=d)

# Basic python file checks
if echo "$files" | grep -q "\.py$"; then
    echo -e "${HD1} Checking python files...${RST}"

    # echo -e "${HD2} Running isort...${RST}"
    # isort .

    # echo -e "${HD2} Running flake8...${RST}"
    # flake8 . --extend-ignore E501

    echo -e "${HD2} Running autoflake...${RST}"
    echo "$files" | xargs python -m autoflake || true

    echo -e "${HD2} Running ruff...${RST}"
    echo "$files" | xargs ruff --config .ruff.toml || true

    echo -e $DNE
fi

# Generate icon font
if echo "$files" | grep -q "^/_static/fonts/TheNestIcons/[^/]+$"; then
    echo -e "${HD1} Generating icon font...${RST}"

    cd src/_static/fonts/TheNestIcons
    python -m nanoemoji.write_font -v 0 --config_file "config.toml" --glyphmap_file "map.glyphmap"

    echo -e $DONE
    cd ../../../
fi

# Generate CSS headers
if echo "$files" | grep -q "^/src/_static/css/styles\.css$"; then
    echo -e "${HD1} Generating CSS headers...${RST}"

    cd .husky/scripts
    python css-toc.py

    echo -e $DONE
    cd ../../
fi

# Run prettier
if echo "$files" | grep -q ".*"; then
    echo -e "${HD1} Running prettier...${RST}"
    echo "$files" | xargs bun prettier --config .prettierrc --ignore-path .prettierignore --write || true

    echo -e $DONE
fi

# Run markdownlint
if echo "$files" | grep -q "\.md$"; then
    echo -e "${HD1} Running markdownlint...${RST}"

    echo "$files" | xargs bun markdownlint --config .markdownlint.json --fix || true

    echo -e $DONE
fi
